// <auto-generated />
using System;
using Khanara.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Khanara.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502205651_CreateCartItemsTableIfNotExists")]
    partial class CreateCartItemsTableIfNotExists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration is a fix for missing CartItems table
            // The model is the same as the previous migration (AddRefreshTokenIndex)
        }
    }
}
